<a href="https://colab.research.google.com/github/yunyonggeun/MLforBioPh/blob/master/01_Study_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이 패키지 배우기

> 넘파이 모듈 불러오기

In [0]:
import numpy as np

## 1. 데이터 생성하기 - 기본

**학습할 함수**
+ np.array([데이터])
+ np.arange(start, end, step)
+ np.ones((row,column))              - 튜플 형태로 행렬 크기를 넘겨줌
+ np.zeros((row,column))
+ np.empty((row,column))
+ np.full((row, column), value)
+ 번수명.reshape(row, column)
+ np.linspace(start, end, value)     - 공간을 주어진 크기로 등분하는 함수

> 1.1. np.array 함수로 생성하기

In [0]:
np.array([1, 2, 3, 4])  # 벡터형태

In [0]:
np.array([[1, 2, 3, 4], [2, 4, 6, 8]]) # 행렬 형태

> 1.2. np.arange 함수 이용하기

In [0]:
np.arange(10)     # 파이썬의 range함수와 동일하다고 함, 값을 하나만 주면 시작 값을 0부터 시작함 

In [0]:
np.arange(2, 20, 2)  # 시작 값, 종료 값, 간격(step), 주의할 점은 종료 값을 포함하지 않음

In [0]:
x3 = np.arange(5, 102, 5)

> 1.3.np.ones / np.zeros : 1 또는 0으로 채워진 벡터나 행렬을 만들어 주는 함수

In [0]:
np.ones((4,5))  # 튜플형태로 생성하기 위한 자료 구조를 넘겨줌 np.zeros

In [0]:
np.ones((4,5,3))

> 1.4. 빈 행렬 생성하기 / 특정 값으로 이루어진 행렬 생성하기

In [0]:
np.empty((3,4))

In [0]:
np.full((3,4), 7)   # 튜플로 행렬 구조를 정의하고 채워질 값을 제시- np.full((행렬 구조), 값)

> 1.5. 단위 행렬 만들기 np.eye(크기) : 단위 행렬은 정방행렬이기 때문에 n X n 형태를 가짐

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

> 1.6. 공간을 주어진 크기로 등분하는 함수 np.linspace(시작, 끝, 분할 크기)

In [4]:
np.linspace(1, 10, 6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

> 1.7.행렬의 차원을 바꾸가 위한 함수 reshape

In [9]:
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## 2. 데이터 생성하기 - random 모듈이용하기

> 2.1. rand 함수 : 0, 1, 사이의 분포로 랜덤한 ndarray 생성

In [11]:
np.random.rand(2,3)              # np.random.rand(행렬 구조)

array([[0.51607801, 0.40434085, 0.34414725],
       [0.78536998, 0.76960134, 0.60948367]])

In [12]:
np.random.rand(2,3,3)   

array([[[0.5209247 , 0.60006994, 0.69401824],
        [0.77156973, 0.85428498, 0.11302936],
        [0.92341089, 0.29323858, 0.76240304]],

       [[0.6906603 , 0.22458216, 0.35848462],
        [0.89028804, 0.91873447, 0.56354004],
        [0.36590433, 0.08609185, 0.62252769]]])

> 2.2. randn 함수: 정규분포로 샘플링된 random ndarray 생성

In [13]:
np.random.randn(10)                   # 1차원 벡터 생성

array([ 0.58678555,  0.26071161, -0.80357725, -1.95946669,  1.18559279,
       -0.29191752,  0.18323271, -0.30814262,  1.77469377, -0.88666516])

In [18]:
np.random.randn(3, 4)                  # 3X4 행렬 생성

array([[-1.63424899,  1.88403421,  0.29010138,  0.02899374],
       [ 1.23606517, -1.12223501,  1.46366489,  1.15968409],
       [-1.31228563,  0.22664963,  0.49798268, -0.60998681]])

In [0]:
np.random.randn(3, 4, 2)                  # 4X2 행렬 3개로 구성된 텐서 생성

> 2.3. randint 함수 : 특정 정수 사이에서 랜덤하게 샘플링

In [0]:
np.random.randint(1, 100, size=(3, 5))   #np.random.randint(low, high, size=(행렬 구조))))    

In [0]:
np.random.randint(1, 10, size=(3,2,2))

> 2.4. seed 함수 : 랜덤한 값을 동일하게 다시 생성하고자 할 때 사용

In [44]:
np.random.seed(100)
np.random.randn(3, 4)           # 실행 전에 seed 함수를 실행하면 반환되는 값이 고정됨


array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

In [45]:
# 위의 함수 실행결과와 비교
np.random.randn(3, 4)

array([[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]])

> 2.5. choice 함수 : 주어진 ndarray에서 제시된 행렬 구조만큼 데이터를 뽑아옴

In [51]:
np.random.choice(45, size=(7))     #np.random.choice(ndarray, size=(행렬 구조)))    

array([ 7, 38, 22, 30, 34, 42, 20])

In [52]:
x = np.array([1, 2, 4, 5, 3, 4, 3 ,4, 6, 8, 8,9])
np.random.choice(x, size=(3,4))

array([[4, 4, 2, 8],
       [3, 8, 3, 1],
       [8, 4, 4, 5]])

In [56]:
y = np.arange(1, 46)
np.random.choice(y, size=(5, 7), replace=False)

array([[10, 24, 22,  9, 42, 40, 32],
       [ 5, 28, 15,  8, 25, 41,  1],
       [44, 35, 36,  2, 34, 39, 17],
       [20, 23, 21,  7, 45,  6, 12],
       [27, 13, 16,  3, 26, 37, 14]])

> 2.6. 확률 분포에 따른 ndarray 생성하기 : uniform / normal etc

In [59]:
np.random.uniform(2, 30, size=(3,4))

array([[29.693999  ,  3.53290065, 19.27620215,  5.145269  ],
       [14.94966421, 22.57637042, 11.41030164, 17.29180304],
       [28.67227176,  5.19632909, 29.50581737, 22.78705627]])

In [60]:
np.random.normal(size=(3,4))

array([[ 0.46841981,  0.70198995,  1.00764969,  0.57674022],
       [-0.96147684, -0.14008023, -0.08469488,  0.35724327],
       [-1.3467309 , -0.2331189 , -0.06486086,  0.9844247 ]])